services:
  - type: web
    name: homework-tracker
    env: node
    plan: free
    buildCommand: npm install --prefix homework-tracker && npm run build --prefix homework-tracker
    startCommand: npm start --prefix homework-tracker
    nodeVersion: 18
    envVars:
      - key: NEXT_PUBLIC_PASTEFY_API_KEY
        value: SU51czLG80VpbMBUGevRgSUVx1lIEZGt5Oe6qjhVktIaXx94moESHANBJL26
